### ISSUE TITLE
Getting Import Error

### ISSUE THREAD

**Issue by ahmedwaqar** [hvg-concordia/ETMA#1]
I cloned the repo and try to install from the instruction. I'm facing the following error:

Traceback (most recent call last):
  File "/home/waqar/Documents/ETMA/ETMA.py", line 2, in <module>
    from start_gui import *
ImportError: bad magic number in 'start_gui': b'\x03\xf3\r\n'

any fix?

**Comment by hvg-concordia** [comment]
Fixed by Sowmith Nethula
